In [3]:
from __future__ import print_function
import torch

In [9]:
# Construct a 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[ 2.7909e+23,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.1019e-44,  0.0000e+00, -3.1723e+37],
        [ 4.5963e-43, -3.1723e+37,  4.5963e-43],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [10]:
# Construct a randomly initialized matrix:
x = torch.rand(6, 3)
print(x)

tensor([[0.1906, 0.3789, 0.5346],
        [0.2763, 0.2229, 0.3404],
        [0.2423, 0.0407, 0.0389],
        [0.4493, 0.9130, 0.0997],
        [0.3610, 0.4645, 0.5015],
        [0.9650, 0.7130, 0.8431]])


In [12]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user



In [15]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [16]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.2137, 0.4474, 0.7161],
        [0.9910, 0.6480, 0.4937],
        [0.3529, 0.7723, 0.3919],
        [0.7645, 0.4533, 0.3141],
        [0.0256, 0.2772, 0.6410]])


Get its size:



In [17]:
print(x.size())

torch.Size([5, 3])


`torch.Size` is in fact a tuple, so it supports all tuple operations.



# Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.



In [20]:
y = torch.rand(5, 3)
print("x:\n", x)
print("y:\n", y)
print(x + y)

x:
 tensor([[0.2137, 0.4474, 0.7161],
        [0.9910, 0.6480, 0.4937],
        [0.3529, 0.7723, 0.3919],
        [0.7645, 0.4533, 0.3141],
        [0.0256, 0.2772, 0.6410]])
y:
 tensor([[0.9055, 0.9447, 0.0622],
        [0.6366, 0.5627, 0.4437],
        [0.8377, 0.3640, 0.3598],
        [0.2233, 0.2881, 0.1757],
        [0.6409, 0.7601, 0.8766]])
tensor([[1.1192, 1.3921, 0.7782],
        [1.6276, 1.2108, 0.9374],
        [1.1907, 1.1364, 0.7517],
        [0.9878, 0.7414, 0.4898],
        [0.6665, 1.0373, 1.5176]])


In [21]:
print(torch.add(x, y))

tensor([[1.1192, 1.3921, 0.7782],
        [1.6276, 1.2108, 0.9374],
        [1.1907, 1.1364, 0.7517],
        [0.9878, 0.7414, 0.4898],
        [0.6665, 1.0373, 1.5176]])


In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.1192, 1.3921, 0.7782],
        [1.6276, 1.2108, 0.9374],
        [1.1907, 1.1364, 0.7517],
        [0.9878, 0.7414, 0.4898],
        [0.6665, 1.0373, 1.5176]])


In [23]:
y.add_(x)
print(y)

tensor([[1.1192, 1.3921, 0.7782],
        [1.6276, 1.2108, 0.9374],
        [1.1907, 1.1364, 0.7517],
        [0.9878, 0.7414, 0.4898],
        [0.6665, 1.0373, 1.5176]])


In [25]:
print("x:\n", x)
print(x[:, 1])

x:
 tensor([[0.2137, 0.4474, 0.7161],
        [0.9910, 0.6480, 0.4937],
        [0.3529, 0.7723, 0.3919],
        [0.7645, 0.4533, 0.3141],
        [0.0256, 0.2772, 0.6410]])
tensor([0.4474, 0.6480, 0.7723, 0.4533, 0.2772])


Resizing: If you want to resize/reshape tensor, you can use torch.view:



In [26]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number



In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4856])
0.4855848252773285


NUMPY BRIDGE
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

# Converting a Torch Tensor to a NumPy Array


In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# Converting NumPy Array to Torch Tensor


See how changing the np array changed the Torch Tensor automatically



In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA TENSORS


In [34]:
print(torch.cuda.is_available())

False
